import { DurableObject } from 'cloudflare:workers';
import { createToken, hashCode } from './protocol.js';
import { rateLimitDecision } from './rate-limit.js';
const WAIT_MS=180000;
const json=(data,status=200)=>Response.json(data,{status,headers:{'cache-control':'no-store'}});
const first=cursor=>cursor.toArray()[0];
export class PairingDirectory extends DurableObject {
  constructor(ctx,env){super(ctx,env);ctx.blockConcurrencyWhile(async()=>{this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS rooms (code_hash TEXT PRIMARY KEY, room_id TEXT NOT NULL, expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS attempts (ip_hash TEXT PRIMARY KEY, window_start INTEGER NOT NULL, joins INTEGER NOT NULL, failures INTEGER NOT NULL, cooldown_until INTEGER NOT NULL)')})}
  async fetch(request){const url=new URL(request.url);if(request.method==='POST'&&url.pathname==='/create')return this.create(request);if(request.method==='POST'&&url.pathname==='/join')return this.join(request);if(request.method==='POST'&&url.pathname==='/consume')return this.consume(request);if(request.method==='POST'&&url.pathname==='/restore')return this.restore(request);return json({error:'not_found'},404)}
  prune(now){this.ctx.storage.sql.exec('DELETE FROM rooms WHERE expires <= ?',now)}
  async create(request){const {ipHash,device,verified=false}=await request.json();const now=Date.now();this.prune(now);if(!this.allow(ipHash,'create',now,verified))return json({error:'turnstile_required'},429);for(let i=0;i<40;i++){const b=new Uint16Array(1);crypto.getRandomValues(b);const code=String(b[0]%1000).padStart(3,'0'),codeHash=await hashCode(code);if(!first(this.ctx.storage.sql.exec('SELECT 1 FROM rooms WHERE code_hash=?',codeHash))){const roomId=crypto.randomUUID(),creatorToken=createToken(),joinerToken=createToken();this.ctx.storage.sql.exec('INSERT INTO rooms VALUES (?,?,?)',codeHash,roomId,now+WAIT_MS);const room=this.env.ROOMS.getByName(roomId);await room.fetch(new Request('https://room/init',{method:'POST',body:JSON.stringify({roomId,codeHash,creatorToken,joinerToken,device,expires:now+WAIT_MS})}));return json({code,roomId,token:creatorToken,expiresAt:now+WAIT_MS})}}return json({error:'codes_exhausted'},503)}
  async join(request){const {codeHash,ipHash,device,verified=false}=await request.json(),now=Date.now();this.prune(now);if(!this.allow(ipHash,'join',now,verified))return json({error:'turnstile_required'},429);const row=first(this.ctx.storage.sql.exec('SELECT room_id,expires FROM rooms WHERE code_hash=?',codeHash));if(!row){this.fail(ipHash);return json({error:'room_unavailable'},404)}return this.env.ROOMS.getByName(row.room_id).fetch(new Request('https://room/request',{method:'POST',body:JSON.stringify({device})}))}
  async consume(request){const {codeHash}=await request.json();this.ctx.storage.sql.exec('DELETE FROM rooms WHERE code_hash=?',codeHash);return json({ok:true})}
  async restore(request){const{codeHash,roomId,expires}=await request.json();if(!codeHash||!roomId||expires<=Date.now())return json({error:'invalid_room'},400);const existing=first(this.ctx.storage.sql.exec('SELECT room_id FROM rooms WHERE code_hash=?',codeHash));if(existing&&existing.room_id!==roomId)return json({error:'code_conflict'},409);this.ctx.storage.sql.exec('INSERT OR REPLACE INTO rooms VALUES (?,?,?)',codeHash,roomId,expires);return json({ok:true})}
  allow(ipHash,kind,now,verified){const row=first(this.ctx.storage.sql.exec('SELECT * FROM attempts WHERE ip_hash=?',ipHash)),decision=rateLimitDecision(row,kind,now,verified);if(!decision.allowed)return false;this.ctx.storage.sql.exec('INSERT INTO attempts VALUES (?,?,?,?,0) ON CONFLICT(ip_hash) DO UPDATE SET window_start=?,joins=?,failures=?,cooldown_until=0',ipHash,decision.windowStart,decision.attempts,decision.failures,decision.windowStart,decision.attempts,decision.failures);return true}
  fail(ipHash){const row=first(this.ctx.storage.sql.exec('SELECT failures FROM attempts WHERE ip_hash=?',ipHash)),failures=(row?.failures||0)+1;this.ctx.storage.sql.exec('UPDATE attempts SET failures=?,cooldown_until=0 WHERE ip_hash=?',failures,ipHash)}
}
